### ISSUE TITLE
Communication issues

### ISSUE THREAD

**Issue by aitorce** [International-Data-Spaces-Association/IDS-AppStore#50]
I am trying to establish communication between the following locally deployed components:
* Dataspace Connector v6.2.0
* Omejdn DAPS v1.3.0
* AppStore v2.0.0

The Dataspace Connector and the Appstore both have access to the Omejdn DAPS. The issue in communication happens when the Dataspace Connector requests the Appstore's IDS description. The Appstore does request a DAT in order to start establishing communication with the Dataspace Connector and this produces a Code 500 on the Dataspace Connector's side.

I requested the description to the following url: https://appstore:8090/api/ids/data ("appstore" being the container name and "8090" as I currently have the Dataspace Connector in 8080).

I have the logs from both parties, Dataspace Connector and Appstore.

Dataspace Connector logs:

```
2022-01-07T11:05:04,315 [scheduling-1] INFO - Scanning agreements...
2022-01-07T11:05:27,736 [https-jsse-nio-8080-exec-5] INFO - Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-01-07T11:05:27,737 [https-jsse-nio-8080-exec-5] INFO - Initializing Servlet 'dispatcherServlet'
2022-01-07T11:05:27,746 [https-jsse-nio-8080-exec-5] INFO - Completed initialization in 8 ms
2022-01-07T11:05:29,262 [https-jsse-nio-8080-exec-5] INFO - Successfully received DAT from DAPS.
2022-01-07T11:05:29,915 [https-jsse-nio-8080-exec-5] INFO - Sending request to https://appstore:8090/api/ids/data ...
2022-01-07T11:05:32,050 [https-jsse-nio-8080-exec-5] ERROR - Received response but response-code not in 200-299! Response-code: 400!
2022-01-07T11:05:32,108 [https-jsse-nio-8080-exec-5] WARN - Message handling or processing failed. [exception=(Unexpected code Response{protocol=http/1.1, code=400, message=, url=https://appstore:8090/api/ids/data} With Body: --lPHzcZGiuvI_M8aaXnkphF5DVUpIJ3Ax-r1gf\r\nContent-Disposition: form-data; name="header"\r\nContent-Type: text/plain;charset=UTF-8\r\nContent-Length: 1084\r\n\r\n{\n  "@context" : {\n    "ids" : "https://w3id.org/idsa/core/",\n    "idsc" : "https://w3id.org/idsa/code/"\n  },\n  "@type" : "ids:RejectionMessage",\n  "@id" : "https://w3id.org/idsa/autogen/rejectionMessage/59bc00eb-12b1-4ed2-a094-8018f552cd33",\n  "ids:rejectionReason" : {\n    "@id" : "https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED"\n  },\n  "ids:senderAgent" : {\n    "@id" : "https://appstore.fit.fraunhofer.de"\n  },\n  "ids:modelVersion" : "4.1.2",\n  "ids:issuerConnector" : {\n    "@id" : "https://appstore.fit.fraunhofer.de"\n  },\n  "ids:securityToken" : {\n    "@type" : "ids:DynamicAttributeToken",\n    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/651dc04f-5d31-405e-b3a2-cfef414f2a50",\n    "ids:tokenValue" : "rejected!",\n    "ids:tokenFormat" : {\n      "@id" : "https://w3id.org/idsa/code/JWT"\n    }\n  },\n  "ids:correlationMessage" : {\n    "@id" : "https://INVALID"\n  },\n  "ids:recipientAgent" : [ ],\n  "ids:recipientConnector" : [ ],\n  "ids:issued" : {\n    "@value" : "2022-01-07T11:05:31.636Z",\n    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"\n  }\n}\r\n--lPHzcZGiuvI_M8aaXnkphF5DVUpIJ3Ax-r1gf\r\nContent-Disposition: form-data; name="payload"\r\nContent-Type: text/plain;charset=UTF-8\r\nContent-Length: 52\r\n\r\nInfomodel Version of incoming Message not supported!\r\n--lPHzcZGiuvI_M8aaXnkphF5DVUpIJ3Ax-r1gf--\r\n)]
java.io.IOException: Unexpected code Response{protocol=http/1.1, code=400, message=, url=https://appstore:8090/api/ids/data} With Body: --lPHzcZGiuvI_M8aaXnkphF5DVUpIJ3Ax-r1gf
Content-Disposition: form-data; name="header"
Content-Type: text/plain;charset=UTF-8
Content-Length: 1084

 {
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:RejectionMessage",
  "@id" : "https://w3id.org/idsa/autogen/rejectionMessage/59bc00eb-12b1-4ed2-a094-8018f552cd33",
  "ids:rejectionReason" : {
    "@id" : "https://w3id.org/idsa/code/VERSION_NOT_SUPPORTED"
  },
  "ids:senderAgent" : {
    "@id" : "https://appstore.fit.fraunhofer.de"
  },
  "ids:modelVersion" : "4.1.2",
  "ids:issuerConnector" : {
    "@id" : "https://appstore.fit.fraunhofer.de"
  },
  "ids:securityToken" : {
    "@type" : "ids:DynamicAttributeToken",
    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/651dc04f-5d31-405e-b3a2-cfef414f2a50",
    "ids:tokenValue" : "rejected!",
    "ids:tokenFormat" : {
      "@id" : "https://w3id.org/idsa/code/JWT"
    }
  },
  "ids:correlationMessage" : {
    "@id" : "https://INVALID"
  },
  "ids:recipientAgent" : [ ],
  "ids:recipientConnector" : [ ],
  "ids:issued" : {
    "@value" : "2022-01-07T11:05:31.636Z",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  }
}
--lPHzcZGiuvI_M8aaXnkphF5DVUpIJ3Ax-r1gf
Content-Disposition: form-data; name="payload"
Content-Type: text/plain;charset=UTF-8
Content-Length: 52

Infomodel Version of incoming Message not supported!
--lPHzcZGiuvI_M8aaXnkphF5DVUpIJ3Ax-r1gf--

        at de.fraunhofer.ids.messaging.protocol.http.IdsHttpService.sendRequest(IdsHttpService.java:371) ~[messaging-4.2.2.jar!/:?]
        at de.fraunhofer.ids.messaging.protocol.http.IdsHttpService.send(IdsHttpService.java:232) ~[messaging-4.2.2.jar!/:?]
        at de.fraunhofer.ids.messaging.protocol.http.IdsHttpService.sendAndCheckDat(IdsHttpService.java:452) ~[messaging-4.2.2.jar!/:?]
        at io.dataspaceconnector.service.message.builder.type.base.AbstractMessageService.send(AbstractMessageService.java:112) [classes!/:6.2.0]
        at io.dataspaceconnector.service.message.builder.type.DescriptionRequestService.sendMessage(DescriptionRequestService.java:92) [classes!/:6.2.0]
        at io.dataspaceconnector.controller.message.ids.DescriptionRequestMessageController.sendMessage(DescriptionRequestMessageController.java:128) [classes!/:6.2.0]
        at io.dataspaceconnector.controller.message.ids.DescriptionRequestMessageController$$FastClassBySpringCGLIB$$ba843bd6.invoke(<generated>) [classes!/:6.2.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) [spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) [spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61) [spring-security-core-5.5.2.jar!/:5.5.2]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) [spring-aop-5.3.9.jar!/:5.3.9]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) [spring-aop-5.3.9.jar!/:5.3.9]
        at io.dataspaceconnector.controller.message.ids.DescriptionRequestMessageController$$EnhancerBySpringCGLIB$$3cbccead.sendMessage(<generated>) [classes!/:6.2.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.52.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.9.jar!/:5.3.9]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.52.jar!/:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:178) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.5.2.jar!/:5.5.2]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.3.9.jar!/:5.3.9]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.5.4.jar!/:2.5.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.9.jar!/:5.3.9]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.9.jar!/:5.3.9]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189) [opentracing-web-servlet-filter-0.4.0.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.52.jar!/:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.52.jar!/:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Appstore logs:

```
2022-01-07T11:05:14,991 [scheduling-1] INFO - Scanning agreements...
2022-01-07T11:05:31,052 [https-jsse-nio-8090-exec-6] INFO - Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-01-07T11:05:31,053 [https-jsse-nio-8090-exec-6] INFO - Initializing Servlet 'dispatcherServlet'
2022-01-07T11:05:31,061 [https-jsse-nio-8090-exec-6] INFO - Completed initialization in 7 ms
2022-01-07T11:05:31,349 [https-jsse-nio-8090-exec-6] INFO - Received incoming message.
2022-01-07T11:06:14,998 [scheduling-1] INFO - Scanning agreements...

```

**Comment by tmberthold** [comment]
`"Infomodel Version of incoming Message not supported!"` -> Please try to add `"4.2.0"` to the `ids:inboundModelVersion`-list of the **AppStores config.json** (Dataspace Connector 6.2.0 is sending messages with `"ids:outboundModelVersion" : "4.2.0"` -> not supported by default AppStore config.json  `ids:inboundModelVersion` -> AppStore sends RejectionMessage because of unsupported incoming infomodel version).

Could look like this in the  **AppStores config.json**:
`"ids:inboundModelVersion" : [ "4.0.0", "4.1.0", "4.1.2", "4.2.0" ]`

**Comment by aitorce** [comment]
Excellent, fixed! Thank you.

**Comment by tmberthold** [comment]
👍
